services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: relaypost_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - relaypost_network

  auth_service:
    build:
      context: ./auth_service

    container_name: auth_service
    restart: unless-stopped

    env_file:
      - ./auth_service/.env

    depends_on:
      postgres:
        condition: service_healthy

    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

    ports:
      - "8000:8000"

    networks:
      - relaypost_network

  content_service:
    build:
      context: ./content_service

    container_name: content_service
    restart: unless-stopped

    # volumes:
    #   - ./content_service:/app

    env_file:
      - ./content_service/.env

    depends_on:
      postgres:
        condition: service_healthy

    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8001"

    ports:
      - "8001:8001"

    networks:
      - relaypost_network

  news_service:
    build:
      context: ./news_service

    container_name: news_service
    restart: unless-stopped

    # volumes:
    #   - ./news_service:/app

    env_file:
      - ./news_service/.env

    depends_on:
      postgres:
        condition: service_healthy

    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8002 --workers 2"

    ports:
      - "8002:8002"

    networks:
      - relaypost_network

  news_generation_service:
    build:
      context: ./news_generation_service

    container_name: news_generation_service
    restart: unless-stopped

    env_file:
      - ./news_generation_service/.env

    depends_on:
      postgres:
        condition: service_healthy

    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8004 --workers 1"

    ports:
      - "8004:8004"

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

    networks:
      - relaypost_network

  tracking_service:
    build:
      context: ./tracking_service

    container_name: tracking_service
    restart: unless-stopped

    env_file:
      - ./tracking_service/.env

    depends_on:
      postgres:
        condition: service_healthy

    command: sh -c "python -c 'from app.models import models; from app.core.database import engine; models.Base.metadata.create_all(bind=engine)' && uvicorn app.main:app --host 0.0.0.0 --port 8003"

    ports:
      - "8003:8003"

    networks:
      - relaypost_network

networks:
  relaypost_network:
    driver: bridge

volumes:
  postgres_data:
