"""Add follow and newsletter features

Revision ID: 5bc18ec14d49
Revises: 86129d3b250a
Create Date: 2026-04-16 00:23:41.184721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc18ec14d49'
down_revision: Union[str, None] = '86129d3b250a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('keywords', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords', 'description')
    op.drop_column('categories', 'image_url')
    # ### end Alembic commands ###
