"""Add SystemCache

Revision ID: 66ea7c14e215
Revises: f486210c9588
Create Date: 2026-07-10 16:10:37.019338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66ea7c14e215'
down_revision: Union[str, None] = 'f486210c9588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_cache',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_cache_key'), 'system_cache', ['key'], unique=False)
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f('ix_system_cache_key'), table_name='system_cache')
    op.drop_table('system_cache')
    # ### end Alembic commands ###
