"""add_deleted_at_to_article

Revision ID: 86129d3b250a
Revises: fa2d94df1e73
Create Date: 2026-04-16 00:00:21.236829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86129d3b250a'
down_revision: Union[str, None] = 'fa2d94df1e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'deleted_at')
    # ### end Alembic commands ###
