"""add_prompt_versions_table

Revision ID: a176259bf9f0
Revises: 5bc18ec14d49
Create Date: 2026-04-17 16:05:32.726379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a176259bf9f0'
down_revision: Union[str, None] = '5bc18ec14d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('changes', sa.String(), nullable=True),
    sa.Column('topic_brainstorm_dynamic', sa.String(), nullable=False),
    sa.Column('content_generation_dynamic', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_id'), 'prompt_versions', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_version'), 'prompt_versions', ['version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_versions_version'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    # ### end Alembic commands ###
