"""Update ReadingHistory for news

Revision ID: d0de1a6648da
Revises: 66ea7c14e215
Create Date: 2026-07-10 16:24:34.480732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0de1a6648da'
down_revision: Union[str, None] = '66ea7c14e215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add source_type with server_default so existing rows don't crash
    op.add_column('reading_history', sa.Column('source_type', sa.String(), server_default='article', nullable=False))
    op.add_column('reading_history', sa.Column('news_article_id', sa.Integer(), nullable=True))
    op.add_column('reading_history', sa.Column('news_title', sa.String(), nullable=True))
    op.add_column('reading_history', sa.Column('news_slug', sa.String(), nullable=True))
    op.alter_column('reading_history', 'article_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reading_history', 'article_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('reading_history', 'news_slug')
    op.drop_column('reading_history', 'news_title')
    op.drop_column('reading_history', 'news_article_id')
    op.drop_column('reading_history', 'source_type')
    # ### end Alembic commands ###
