"""update_saved_articles_and_bookmarks

Revision ID: f486210c9588
Revises: a176259bf9f0
Create Date: 2026-07-09 11:33:14.064748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f486210c9588'
down_revision: Union[str, None] = 'a176259bf9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bookmark_folders',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('is_smart', sa.Boolean(), nullable=True),
        sa.Column('auto_sort_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmark_folders_id'), 'bookmark_folders', ['id'], unique=False)
    op.create_index(op.f('ix_bookmark_folders_user_id'), 'bookmark_folders', ['user_id'], unique=False)

    op.create_table(
        'bookmark_tags',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmark_tags_id'), 'bookmark_tags', ['id'], unique=False)
    op.create_index(op.f('ix_bookmark_tags_user_id'), 'bookmark_tags', ['user_id'], unique=False)
    op.add_column('saved_articles', sa.Column('source_type', sa.String(), server_default='article', nullable=False))
    op.add_column('saved_articles', sa.Column('news_article_id', sa.Integer(), nullable=True))
    op.add_column('saved_articles', sa.Column('news_title', sa.String(), nullable=True))
    op.add_column('saved_articles', sa.Column('news_slug', sa.String(), nullable=True))
    op.add_column('saved_articles', sa.Column('news_image_url', sa.String(), nullable=True))
    op.add_column('saved_articles', sa.Column('news_source', sa.String(), nullable=True))
    op.add_column('saved_articles', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.add_column('saved_articles', sa.Column('tag_ids', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('saved_articles', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('saved_articles', 'article_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'saved_articles', 'bookmark_folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_articles', type_='foreignkey')
    op.alter_column('saved_articles', 'article_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('saved_articles', 'notes')
    op.drop_column('saved_articles', 'tag_ids')
    op.drop_column('saved_articles', 'folder_id')
    op.drop_column('saved_articles', 'news_source')
    op.drop_column('saved_articles', 'news_image_url')
    op.drop_column('saved_articles', 'news_slug')
    op.drop_column('saved_articles', 'news_title')
    op.drop_column('saved_articles', 'news_article_id')
    op.drop_column('saved_articles', 'source_type')
    # ### end Alembic commands ###
