"""Add HalfVector embedding and HNSW index

Revision ID: 2a0464a9b8cc
Revises: dbb4c94be41c
Create Date: 2026-07-16 06:25:18.860585

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '2a0464a9b8cc'
down_revision = 'dbb4c94be41c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.add_column('articles', sa.Column('embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=384), nullable=True))
    op.create_index('article_embedding_idx', 'articles', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'halfvec_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('article_embedding_idx', table_name='articles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'halfvec_cosine_ops'})
    op.drop_column('articles', 'embedding')
    # ### end Alembic commands ###
