import os
import re
import json
import base64
import requests
from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from pathlib import Path

from app.crud import crud
from app.models import models
from app.services.automation.tools import GeminiTool

class SelfLearningEngine:
    def __init__(self, db: Session):
        self.db = db
        self.gemini = GeminiTool()
        # Find paths correctly, assuming learning.py is in automation folder
        self.automation_dir = Path(__file__).parent.absolute()
        self.prompts_file_path = self.automation_dir / "prompts.py"

    async def analyze_and_update_prompt(self):
        """Analyzes recent articles and dynamically updates prompts if needed."""
        print(f"[{datetime.now()}] Starting Self-Learning Loop...")
        try:
            # 1. Fetch articles generated in the last 24 hours
            yesterday = datetime.utcnow() - timedelta(days=1)
            recent_articles = self.db.query(models.Article).filter(
                models.Article.created_at >= yesterday
            ).all()

            if not recent_articles:
                print("No articles found. Skipping learning loop.")
                return

            articles_summary = []
            for a in recent_articles:
                articles_summary.append({
                    "title": a.title,
                    "category": a.category.name if a.category else "Uncategorized",
                    "template": a.template_type,
                    "excerpt": a.excerpt
                })

            # Fetch current dynamic prompts from DB, fallback to prompts.py
            latest_prompt = crud.get_latest_prompt_version(self.db)
            if latest_prompt:
                current_topic_prompt = latest_prompt.topic_brainstorm_dynamic
                current_content_prompt = latest_prompt.content_generation_dynamic
                current_version = latest_prompt.version
            else:
                from app.services.automation.prompts import TOPIC_BRAINSTORM_DYNAMIC_PROMPT, CONTENT_GENERATION_DYNAMIC_PROMPT
                current_topic_prompt = TOPIC_BRAINSTORM_DYNAMIC_PROMPT
                current_content_prompt = CONTENT_GENERATION_DYNAMIC_PROMPT
                current_version = "v0"

            # 2. Ask Gemini to evaluate
            evaluation_prompt = f"""
            You are an AI Quality Assurance System for RelayPost Intelligence.
            Your task is to analyze the daily output of articles generated by the system and recalibrate the system prompt to fix any detected biases or quality issues.

            RECENT ARTICLES (Last 24h):
            {json.dumps(articles_summary, indent=2)}

            CURRENT TOPIC_BRAINSTORM_DYNAMIC_PROMPT:
            {current_topic_prompt}

            CURRENT CONTENT_GENERATION_DYNAMIC_PROMPT:
            {current_content_prompt}

            EVALUATION PARAMETERS:
            1. Repetitiveness: Are the topics too similar?
            2. Humanization: Does the tone sound robotic or like AI clichés?
            3. Domain Focus: Evaluate if the platform is understanding its core. 'Tech' and 'AI' MUST remain the absolute highest priority and core focus of the system. Ensure the prompt does not deprioritize them.
            4. Geo Bias: Are the articles solely US-centric? They should be targeted towards an Indian or global audience without ignoring other regions.

            INSTRUCTIONS:
            Based on your evaluation, output a JSON with:
            - "evaluation_response": A short summary of biases found or quality notes.
            - "score": 1-10 quality score.
            - "needs_update": true or false. True if the biases are too strong and we need to tweak the prompt weightings.
            - "new_topic_brainstorm_dynamic": If needs_update is true, provide a completely rewritten TOPIC_BRAINSTORM_DYNAMIC_PROMPT string (plain text) to replace the old one. Use strong language to fix the detected bias. DO NOT USE ``` in the string.
            - "new_content_generation_dynamic": If needs_update is true, provide a rewritten CONTENT_GENERATION_DYNAMIC_PROMPT string (plain text). DO NOT USE ``` in the string.
            """

            result = await self.gemini.generate_structured(evaluation_prompt, temperature=0.7)
            if isinstance(result, list) and len(result) > 0:
                for item in result:
                    if isinstance(item, dict):
                        result = item
                        break
            if not isinstance(result, dict):
                result = {}
            
            print(f"Self-Learning Evaluation Score: {result.get('score', 'N/A')} / 10")
            print(f"Notes: {result.get('evaluation_response', 'N/A')}")

            needs_update = result.get("needs_update", False)
            if not needs_update:
                print("Gemini determined no prompt update is needed today.")
                return

            new_topic_dynamic = result.get("new_topic_brainstorm_dynamic")
            new_content_dynamic = result.get("new_content_generation_dynamic")

            if new_topic_dynamic and new_content_dynamic:
                # 3. Calculate next version string (e.g. v1 -> v2)
                try:
                    v_num = int(current_version.replace('v', ''))
                    next_version = f"v{v_num + 1}"
                except ValueError:
                    next_version = f"v{len(current_version) + 1}"
                
                # 4. Save to DB
                import schemas
                new_version_data = schemas.PromptVersionCreate(
                    version=next_version,
                    score=float(result.get("score")) if result.get("score") else None,
                    changes=result.get("evaluation_response"),
                    topic_brainstorm_dynamic=new_topic_dynamic,
                    content_generation_dynamic=new_content_dynamic
                )
                crud.create_prompt_version(self.db, new_version_data)
                
                print(f"Successfully recorded new prompt version {next_version} in the database.")

        except Exception as e:
            print(f"Self-Learning Engine Failed: {e}")
            import traceback
            traceback.print_exc()

