"""add_seo_fields

Revision ID: 0c973abfceb6
Revises: 768512b36a41
Create Date: 2026-05-04 09:28:50.918766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c973abfceb6'
down_revision = '768512b36a41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('meta_title', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('meta_description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_column('articles', 'meta_description')
    op.drop_column('articles', 'meta_title')
    op.drop_column('articles', 'slug')
    # ### end Alembic commands ###
