"""add views to articles and systemcache

Revision ID: dbb4c94be41c
Revises: ee5c250d008d
Create Date: 2026-07-13 16:22:44.234440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb4c94be41c'
down_revision = 'ee5c250d008d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('views', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'views')
    # ### end Alembic commands ###
