"""add password reset columns

Revision ID: 8d2b1e920cf5
Revises: b8dbd6e23499
Create Date: 2026-07-12 01:05:10.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2b1e920cf5'
down_revision: Union[str, None] = 'b8dbd6e23499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_otp_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_otp_expires_at')
    op.drop_column('users', 'reset_otp_hash')
    # ### end Alembic commands ###
